version: "3.1"
services:

    redis:
      image: redis:alpine
      container_name: crm-redis
      ports:
        - "6379:6379"

    webserver:
      image: abiosoft/caddy:0.11.0
      container_name: crm-webserver
      ports:
          - "80:80"
          - "443:443"
      volumes:
          - ./phpdocker/caddy/Caddyfile:/etc/Caddyfile
          - ./.caddy:/root/.caddy
          - .:/application
      dns: 8.8.8.8

    php-fpm:
      build: phpdocker/php-fpm
      container_name: crm-php-fpm
      working_dir: /application
      volumes:
        - .:/application
        - ./phpdocker/php-fpm/php-ini-overrides.ini:/usr/local/etc/php/conf.d/99-overrides.ini
      links:
        - redis:redis
      dns: 8.8.8.8
